// DashboardLayout.tsx
import React, { ReactNode } from "react";
import { Tabs } from "@/components/ui/tabs";
export const metadata = {
  title: "Dashboard | To Do App",
  description: "Generated by create next app",
};

type DashboardLayoutProps = {
  children: ReactNode;
};

const DashboardLayout = ({ children }: DashboardLayoutProps) => {
  return (
    <>
      <Tabs
        defaultValue="overview"
        className="min-h-screen  xl:mx-10  xl:my-5 "
      >
        {children}
      </Tabs>
    </>
  );
};

export default DashboardLayout;
